replaceitem entity @s slot.hotbar 0 barrier
replaceitem entity @s slot.hotbar 1 barrier
replaceitem entity @s slot.hotbar 2 barrier
replaceitem entity @s slot.hotbar 3 barrier
replaceitem entity @s slot.hotbar 4 barrier
replaceitem entity @s slot.hotbar 5 barrier
replaceitem entity @s slot.hotbar 6 barrier
replaceitem entity @s slot.hotbar 7 barrier
replaceitem entity @s slot.hotbar 8 barrier
